### ISSUE TITLE
gnubiff-xfce cppcheck

### ISSUE THREAD

**Issue by IgorPolyakov** [zeldin/gnubiff-xfce#1]
Hello! Project is still alive?

I found some errors)

[src/decoding.cc:892]: (error) Memory leak: bin
[src/decoding.cc:911]: (error) Mismatching allocation and deallocation: bin
[src/decoding.cc:912]: (error) Mismatching allocation and deallocation: result
[src/decoding.cc:970]: (error) Mismatching allocation and deallocation: result
[src/mailbox.cc:507]: (error) Array 'prt[6]' accessed at index 6, which is out of bounds.
[src/mailbox.cc:509]: (error) Array 'ssl[6]' accessed at index 6, which is out of bounds.
[src/mailbox.cc:1269]: (error) Mismatching allocation and deallocation: buffer
[src/socket.cc:285]: (error) Memory leak: err_buf
[src/socket.cc:329]: (error) Memory leak: err_buf

Can I create a pull request, and fix it?

**Comment by zeldin** [comment]
Certainly!  Improvements are very welcome.
